<?php defined('BASEPATH') OR exit('No direct script access allowed');?>


<div id="printMe" style=" margin: 0px 30px 0px 30px ">
<div class=" row bg-success" style="padding-bottom: 10px ">
                       
        <h2 class="text-center text-success"><strong><?php 
        echo 'Automatic Narration Generation';?></strong></h2>           
        <?php
        $enddate1 = date('Y-m-d',strtotime("now"));
        $enddate = date('Y-m-d',strtotime("$enddate1 -1 day"));
        $startdate1 = $enddate;           
        $startdate2 = date('M.d',strtotime("$enddate -1 week"));
        $startdate3 = date('M.d,Y',strtotime("$startdate1"));?>
        <h3 class="text-center"><?php 
       
            echo "punjabupdate.com website data";
       
        ?></h3>
    
        <h4 class="text-center"><?php          ;
        echo  'Week of '.$startdate2.' - '.$startdate3; ?></h4> 
<h5 class="text-right"><?php echo " Generated by Delphi based Narrator";?> </h5>
</div>
<div class = "row">
<table class ="table table-bordered table-striped">
<thead><tr><h5><th>Metric</th>
            <th>Current week value</th>
            <th> Rate of change</th></h5>
            </tr>
</thead>
<tbody>
<tr><td> <?php echo "Primary Content Consumption";?></td>
<td> <?php
            echo $current_week['primary_content_consumption'];
    ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['primary_content_consumption'] > 0)
            {         
            echo $rateofchange['primary_content_consumption']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['primary_content_consumption'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['primary_content_consumption']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['primary_content_consumption']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr> 
    <td><?php echo "Repeat Visitor Ratio";?></td>
    <td>
        <?php
            echo $current_week['repeat_visitor_ratio']." % ";
        ?></td>
   <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['repeat_visitor_ratio'] > 0)
            {         
            echo $rateofchange['repeat_visitor_ratio']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['repeat_visitor_ratio'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['repeat_visitor_ratio']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['repeat_visitor_ratio']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

 <tr> <td colspan="3"></td></tr>
<tr class="text-center">  <td colspan="3"><?php echo "Event Conversion Rate";?></td></tr>
<tr> 
    <td><?php echo "Sessions with Events";?></td>
    <td>
        <?php
            echo $current_week['sessions_with_events']." sessions";
        ?></td>
     <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['sessions_with_events'] > 0)
            {         
            echo $rateofchange['sessions_with_events']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['sessions_with_events'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['sessions_with_events']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['sessions_with_events']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr> 
    <td><?php echo "Conversion Rate";?></td>
    <td>
        <?php
            echo $current_week['conversion_rate']."% ";
        ?></td>
     <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['conversion_rate'] > 0)
            {         
            echo $rateofchange['conversion_rate']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['conversion_rate'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['conversion_rate']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['conversion_rate']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr> <td colspan="3"></td></tr>

<tr><td><?php echo "Bounce Rate";?></td>
    <td>
        <?php
            echo $current_week['bounce_rate']."% ";
        ?></td>
     <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['bounce_rate'] > 0)
            {         
            echo $rateofchange['bounce_rate']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['bounce_rate'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['bounce_rate']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['bounce_rate']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>


<tr> <td colspan="3"></td></tr>
<tr class="text-center">  <td colspan="3"><?php echo "Basic Metrics";?></td></tr>
<tr><td><?php echo "Sessions";?></td>
    <td>
        <?php
            echo $current_week['sessions']." sessions";
        ?></td>
<td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['sessions'] > 0)
            {         
            echo $rateofchange['sessions']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['sessions'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['sessions']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['sessions']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr><td><?php echo "Users";?></td>
    <td>
        <?php
            echo $current_week['users']." users";
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['users'] > 0)
            {         
            echo $rateofchange['users']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['users'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['users']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['users']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr><td><?php echo "Pageviews";?></td>
    <td>
        <?php
            echo $current_week['pageviews']." pageviews";
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['pageviews'] > 0)
            {         
            echo $rateofchange['pageviews']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['pageviews'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['pageviews']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['pageviews']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr><td><?php echo "Unique Pageviews";?></td>
    <td>
        <?php
            echo $current_week['unique_pageviews']." unique pageviews";
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['unique_pageviews'] > 0)
            {         
            echo $rateofchange['unique_pageviews']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['unique_pageviews'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['unique_pageviews']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['unique_pageviews']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr><td><?php echo "Exit Rate";?></td>
    <td>
        <?php
            echo $current_week['exit_rate']." % ";
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['exit_rate'] > 0)
            {         
            echo $rateofchange['exit_rate']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['exit_rate'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['exit_rate']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['exit_rate']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr><td><?php echo "Average Session Duration";?></td>
    <td>
        <?php
            echo $current_week['average_session_duration']." sec";
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['average_session_duration'] > 0)
            {         
            echo $rateofchange['average_session_duration']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['average_session_duration'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['average_session_duration']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['average_session_duration']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr><td><?php echo "New Visitor Percentage";?></td>
    <td>
        <?php
            echo $current_week['new_visitor_percentage']." % ";
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['new_visitor_percentage'] > 0)
            {         
            echo $rateofchange['new_visitor_percentage']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['new_visitor_percentage'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['new_visitor_percentage']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['new_visitor_percentage']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr><td><?php echo "Sessions per User";?></td>
    <td>
        <?php
            echo $current_week['sessions_per_user']." sessions";
        ?></td>
   <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['sessions_per_user'] > 0)
            {         
            echo $rateofchange['sessions_per_user']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['sessions_per_user'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['sessions_per_user']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['sessions_per_user']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr><td><?php echo "Entry to Exit Ratio";?></td>
    <td>
        <?php
            echo $current_week['entry_to_exit_ratio'];
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['entry_to_exit_ratio'] > 0)
            {         
            echo $rateofchange['entry_to_exit_ratio']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['entry_to_exit_ratio'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['entry_to_exit_ratio']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['entry_to_exit_ratio']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr> <td colspan="3"></td></tr>

<tr><td><?php echo "Visitor Engagement Degree";?></td>
    <td>
        <?php
            echo $current_week['visitor_Engagement_Degree'];
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['visitor_Engagement_Degree'] > 0)
            {         
            echo $rateofchange['visitor_Engagement_Degree']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['visitor_Engagement_Degree'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['visitor_Engagement_Degree']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['visitor_Engagement_Degree']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr> <td colspan="3"></td></tr>
<tr class="text-center">  <td colspan="3"><?php echo "Navigation";?></td></tr>
<tr><td><?php echo "PathLoss";?></td>
    <td>
        <?php
            echo $current_week['pathloss']." % ";
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['pathloss'] > 0)
            {         
            echo $rateofchange['pathloss']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['pathloss'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['pathloss']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['pathloss']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr><td><?php echo "Traffic Concentration";?></td>
    <td>
        <?php
            echo $current_week['traffic_concentration']." % ";
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['traffic_concentration'] > 0)
            {         
            echo $rateofchange['traffic_concentration']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['traffic_concentration'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['traffic_concentration']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['traffic_concentration']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr> <td colspan="3"></td></tr>
<tr class="text-center">  <td colspan="3"><?php echo "Mobile Readiness";?></td></tr>
<tr><td><?php echo "Mobile Users";?></td>
    <td>
        <?php
            echo $current_week['mobile_users']." users";
        ?></td>
   <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['mobile_users'] > 0)
            {         
            echo $rateofchange['mobile_users']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['mobile_users'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['mobile_users']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['mobile_users']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr><td><?php echo "Desktop Users";?></td>
    <td>
        <?php
            echo $current_week['desktop_users']." users";
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['desktop_users'] > 0)
            {         
            echo $rateofchange['desktop_users']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['desktop_users'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['desktop_users']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['desktop_users']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr><td><?php echo "Tablet Users";?></td>
    <td>
        <?php
            echo $current_week['tablet_users']." users";
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['tablet_users'] > 0)
            {         
            echo $rateofchange['tablet_users']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['tablet_users'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['tablet_users']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['tablet_users']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr> <td colspan="3"></td></tr>
<tr><td><?php echo "Page Depth";?></td>
    <td>
        <?php
            echo $current_week['page_depth'];
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['page_depth'] > 0)
            {         
            echo $rateofchange['page_depth']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['page_depth'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['page_depth']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['page_depth']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>

<tr><td><?php echo "Landing Page Users";?></td>
    <td>
        <?php
            echo $current_week['landing_page_users']." users";
        ?></td>
    <td>   <span class="text-success"> <strong>

        <?php
            if($rateofchange['landing_page_users'] > 0)
            {         
            echo $rateofchange['landing_page_users']." % " ;?><span
            class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            </strong></span><?php
            }
            elseif($rateofchange['landing_page_users'] == 0)
            {
           ?>
            <span class="text-warning"> <strong><?php
            echo $rateofchange['landing_page_users']."%"." change";
            }
            else
            { ?> </strong></span>
        <span class="text-danger"><strong><?php                      
            echo $rateofchange['landing_page_users']." % ";;?><span
            class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span><?php
            }
        ?> </strong>
         </span> <span> <?php echo " from last week";?></span></td>
</tr>


</tbody>
</table>

</div>



<div class="bs-callout bs-callout-success">
        <h4 class="text-center"> <?php echo "Primary Content Consumption";?> </h4> 
               
        <div class="text-justify">
        <?php echo $fetch_narration['primary_content_consumption'];?>
        </div>   
</div>
<div class="bs-callout bs-callout-success">
        <h4 class="text-center"> <?php echo "Repeat Visitor Ratio";?> </h4> 
             
        <div class="text-justify">
        <?php echo $fetch_narration['repeat_visitor_ratio'];?>
        </div>   
</div>
<div class="bs-callout bs-callout-primary">
        <h3 class="text-center"> <?php echo "Event Conversion Rate";?> </h3> 
        <h4 class="text-center"> <?php echo "Sessions with Events";?> </h4>  
        <div class="text-justify">
        <?php echo $fetch_narration['sessions_with_events'];?>
        </div> 
        <div class="text-justify">
        <h4 class="text-center"> <?php echo "Desired Action Percentage";?> </h4> 
        <?php echo $fetch_narration['conversion_rate'];?>
        </div>   
</div>
<div class="bs-callout bs-callout-success">
        <h4 class="text-center"> <?php echo "Bounce Rate";?> </h4> 
             
        <div class="text-justify">
        <?php echo $fetch_narration['bounce_rate'];?>
        </div>   
</div>
<div class="bs-callout bs-callout-muted">
        <h3 class="text-center"> <?php echo "Basic Metrics";?> </h3> 
        <h4 class="text-center"> <?php echo "Sessions";?> </h4>  
        <div class="text-justify">
        <?php echo $fetch_narration['sessions'];?>
        </div> 
        <div class="text-justify">
        <h4 class="text-center"> <?php echo "Users";?> </h4> 
        <?php echo $fetch_narration['users'];?>
        </div>  
        <div class="text-justify">
        <h4 class="text-center"> <?php echo "Pageviews";?> </h4> 
        <?php echo $fetch_narration['pageviews'];?>
        </div>
         <div class="text-justify">
        <h4 class="text-center"> <?php echo "Unique Pageviews";?> </h4> 
        <?php echo $fetch_narration['unique_pageviews'];?>
        </div> 
        <div class="text-justify">
        <h4 class="text-center"> <?php echo "Exit Rate";?> </h4> 
        <?php echo $fetch_narration['exit_rate'];?>
        </div>
        <div class="text-justify">
        <h4 class="text-center"> <?php echo "Average Session Duration";?> </h4> 
        <?php echo $fetch_narration['average_session_duration'];?>
        </div>
        <div class="text-justify">
        <h4 class="text-center"> <?php echo "New Visitor Percentage";?> </h4> 
        <?php echo $fetch_narration['new_visitor_percentage'];?>
        </div>
        <div class="text-justify">
        <h4 class="text-center"> <?php echo "Sessions per User";?> </h4> 
        <?php echo $fetch_narration['sessions_per_user'];?>
        </div> 
        <div class="text-justify">
        <h4 class="text-center"> <?php echo "Entry to Exit Ratio";?> </h4> 
        <?php echo $fetch_narration['entry_to_exit_ratio'];?>
        </div>

</div>
<div class="bs-callout bs-callout-success">
        <h4 class="text-center"> <?php echo "Visitor Engagement Degree";?> </h4> 
             
        <div class="text-justify">
        <?php echo $fetch_narration['visitor_Engagement_Degree'];?>
        </div>   
</div>
<div class="bs-callout bs-callout-warning">
        <h3 class="text-center"> <?php echo "Navigation";?> </h3> 
        <h4 class="text-center"> <?php echo "PathLoss";?> </h4>  
        <div class="text-justify">
        <?php echo $fetch_narration['pathloss'];?>
        </div> 
        <div class="text-justify">
        <h4 class="text-center"> <?php echo "Traffic Concentration";?> </h4> 
        <?php echo $fetch_narration['traffic_concentration'];?>
        </div> 
</div>
<div class="bs-callout bs-callout-success">
        <h4 class="text-center"> <?php echo "Page Depth";?> </h4> 
             
        <div class="text-justify">
        <?php echo $fetch_narration['page_depth'];?>
        </div>   
</div>
<div class="bs-callout bs-callout-default">
        <h4 class="text-center"> <?php echo "Landing Page Users";?> </h4> 
             
        <div class="text-justify">
        <?php echo $fetch_narration['landing_page_users'];?>
        </div>   
</div>
</div>
<div class="text-right"><button class="btn btn-primary" id="print_btn">Print</button></div>





   
