<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

//adding config items.
$config['site'] = array(

	// Site name
	'name' => 'Narration Generation System',

	'short_name' => 'NGS',

	// Default page title
	// (set empty then MY_Controller will automatically generate one according to controller / action)
	'title' => '',

	// Multilingual settings (set empty array to disable this)
	'multilingual' => array(	// language files to autoload
	),

	// Google Analytics User ID (UA-XXXXXXXX-X)
	'ga_id' => '',
	
	// Menu items
	// 
	'admin_menu' => array(
			'overview' => array(
				'name'		=> 'Overview',
				'url'		=> 'admin',
				//'icon'		=> 'fa fa-home',
			),
			
			'data1' => array(
			'name'		=> 'website- punjabupdate.com',
			'url'		=> 'admin',
			'children'  => array(
				'Data' => 'admin/punjabdata/punjabdata',
				'Data continued' => 'admin/punjabdata2/punjabdata'
					 )	
			),
			
		
			'data2' => array(
			'name'		=> 'website- ijorcs.org',
				'url'		=> 'admin/ijorcsdata/ijorcsdata',
				'children'  => array(
				'Data' => 'admin/ijorcsdata/ijorcsdata',
				'Data continued' => 'admin/ijorcsdata2/ijorcsdata'
				)	
			),
			
			'data3' => array(
			'name'		=> 'Narration metrics',
				'url'		=> 'admin/narrationmetrics/metrics',	
			),
				
			'reportsetting' => array(
				'name'		=> 'Report',
				'url'		=> 'admin/report',
				//'icon'		=> 'fa fa-users',
				/*'children'  => array(
					'Report' => 'admin/report',
					'threshold_range'	=> 'admin/threshold', )*/
			),
						
			
			'tree' => array(
			'name'		=> 'Autogenerated Tree',
				'url'		=> 'admin/autogentree/autogenerated_tree',	
			),
			/*'databasevalues' => array(
				'name'		=> 'Database',
				'url'		=> 'database',
				//'icon'		=> 'ion ion-gear-b',	// use Ionicons (instead of FontAwesome)
				'children'  => array(
					'Conditions'	=> 'admin/database/conditions',
					'Narration Details'		=> 'admin/database/narrationdetails',
					'Narration Titles'		=> 'admin/database/narrationtitles',
					'Narrativetype Details'		=> 'admin/database/narrativetypedetails',
					'Rules Applied'		=> 'admin/database/rules',
					'Section Details'		=> 'admin/database/sectiondetails',	
					'Ruleset'		=> 'admin/database/ruleset',
				)
			),*/

			'qfd' => array(
				'name'		=> 'Agreement',
				'url'		=> 'qqfd',
				//'icon'		=> 'ion ion-gear-b',	// use Ionicons (instead of FontAwesome)
				'children'  => array(
					'Raters' => 'admin/questionnaires/users',
					'Final responses' => 'admin/questionnaires/responses',
					'Degree of agreement' => 'admin/questionnaire/qfd',
					'Cutt-off values' => 'admin/precedence/priority',				
					
					'All questions precedence' =>'admin/questionnaires/priority',

					'Final questions precendence' => 'admin/questionnaires/priority2',
					'Final questions with sum of precedence' => 'admin/questionnaires/relevant',
					
					)
				),
			'questionnaires' => array(
				'name'		=> 'Questionnaire data',
				'url'		=> 'questionnaires',
				//'icon'		=> 'ion ion-gear-b',	// use Ionicons (instead of FontAwesome)
				'children'  => array(
					'Questionnaire No'	=> 'admin/questionnaires/questionnairesone',
					'Scales'	=> 'admin/questionnaires/scales',
					'Questions'		=> 'admin/questionnaires/questions',
					'Individual user response'		=> 'admin/questionnaires/responsetable',
					
					
					)
				),
			'questionnaires1' => array(
				'name'		=> 'Questionnaires',
				'url'		=> 'questionnaire',
				//'icon'		=> 'ion ion-gear-b',	// use Ionicons (instead of FontAwesome)
				'children'  => array(
					'Questionnaire No.1'	=> 'admin/questionnaire',
					
					)
				),
			/*'forms4' => array(
				'name'		=> 'Aknowledgements & Credits',
				'url'		=> 'datacenterseting',
			//	'icon'		=> 'ion ion-gear-b',	// use non-FontAwesome icon (with "icon" class to align styling)
				'children'  => array(
					'Aknowledgements'	=> 'Others/acknowledgements',
					'Credits'	=> 'Others/credits',
					'Publications'	=> 'Others/publication',
					'References'  => 'Others/reference',
				    'Resources'  => 'Others/resources',
					
					 				
				),
	        ),*/
			
			
		),

		
		'member_menu' => array(
			
			'questionnaires1' => array(
				'name'		=> 'Questionnaires',
				'url'		=> 'questionnaire',
				//'icon'		=> 'ion ion-gear-b',	// use Ionicons (instead of FontAwesome)
				'children'  => array(
					'Questionnaire No. 1'	=> 'admin/questionnaire',
					
					)
				),
			
			
		),



	
	
);
