<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Autogentree extends Admin_Controller {

	public function __construct()
	{

		parent::__construct();
		$this->load->library('grocery_CRUD');
		
		
	}
		public function index()
	{
		
	}


	public function autogenerated_tree()
	{
		$this->data['page_title'] = 'Autogenerated Tree';

		$crud = new grocery_CRUD();
		$crud->set_table('autogeneratetree');
		$crud->set_subject('attributes');
		
		$crud->set_relation('parent_id','autogeneratetree','nodename');	
		 $crud->unset_edit()
         ->unset_delete()
         ->unset_read();


		$this->data['output'] = $crud->render();
		$this->render('admin/crud_view');
	}
}